import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import LifeAni from "../animations/LifeAni";
import Me from "../animations/Me";
import MotionAni from "../animations/MotionAni";
import ProductAni from "../animations/ProductAni";
import VideoAni from "../animations/VideoAni";
import { client } from "../data/client";
import GetStoriesByTag from "../data/GetStoriesByTag";
import IStory from "../types/Story";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Drew Lytle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section className="h-screen top-section">
          <div className="h-full relative flex flex-col items-center">
            <div className="tilted-header flex-grow-0">
              <div>
                <h5>HEY, FRIEND 👋</h5>
                <h2>MY NAME’S DREW</h2>
              </div>
            </div>
            <div className="flex justify-center flex-grow w-full pb-4">
              <Me />
            </div>
            <div className="flex-grow-0 flex flex-col items-center text-gray-500 pb-2">
              <div className="header-font text-sm uppercase">scroll down</div>
              <div>
                <i className="bi bi-mouse-fill"></i>
              </div>
            </div>
          </div>
        </section>
        <section className="h-screen flex flex-col items-center justify-center">
          <div>
            <div className="tilted-header mb-4">
              <h1>I{"'"}M A...</h1>
            </div>
            <div className="pt-4 flex flex-col items-center space-y-14">
              <ProductAni link="#product" />
              <VideoAni link="#video" />
              <div className="pt-2">
                <h2 className="leading-0.75 inline-block mr-3">&</h2>
                <MotionAni link="#motion" />
              </div>
              <div className="pt-2">
                <h2 className="leading-0.75 inline-block mr-3">in</h2>
                <LifeAni link="#life" />
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { stories: softwareStories }: { stories: [IStory] } =
    await client.request(GetStoriesByTag, {
      tags: ["software"]
    });
  const { stories: videoStories }: { stories: [IStory] } = await client.request(
    GetStoriesByTag,
    {
      tags: ["video"]
    }
  );
  const { stories: motionStories }: { stories: [IStory] } =
    await client.request(GetStoriesByTag, {
      tags: ["motion"]
    });
  const { stories: lifeStories }: { stories: [IStory] } = await client.request(
    GetStoriesByTag,
    {
      tags: ["life"]
    }
  );

  // Provide Props to the Page Component
  return {
    props: {
      softwareStories,
      videoStories,
      motionStories,
      lifeStories
    },
    revalidate: 60 * 60 // Cache response for 1 hour (60 seconds * 60 minutes)
  };
};

export default Home;
